"""Data definitions for KLTN RL Matching Excel Workbook."""

WEEKS_DATA = [
    ("Tuần 1", "21/09 - 27/09/2026", "Bước 1 & 2: Problem Formulation & Architecture Setup",
     "Trả lời 6 câu hỏi nền tảng; Formalize MDP (State, Action, Reward, Loss); Audit curated dataset; Thiết lập Baseline Exact Hungarian",
     "SV/GV nhận features gì? Loss & Reward như thế nào? Tại sao multi-turn MDP khác hồi quy 1 vòng? Target accuracy?",
     "Hoàn thành doc trả lời 6 câu hỏi; Chạy được Hungarian baseline trên train/val/test; Pipeline chia tập ổn định", "Hoàn thành"),
    ("Tuần 2", "28/09 - 04/10/2026", "Bước 2 & 3: Data Cleaning, Audit & Feature Representation",
     "Hoàn thiện Data Contract; Feature engineering: TF-IDF vs Vietnamese Sentence-Transformers; Chuẩn hoá skill evidence matrix",
     "Biểu diễn text nào tối ưu chống overfitting? Vector size của Observation space? Xử lý từ đồng nghĩa kỹ năng?",
     "Ma trận Compatibility đạt shape (N, M), zero NaN, zero data leakage giữa train và val/test", "Đang thực hiện"),
    ("Tuần 3", "05/10 - 11/10/2026", "Bước 4 & 5: Gymnasium Environment & Multi-Objective Reward",
     "Xây dựng GymMatchingEnv v2; Thiết kế Action Masking; Implement Reward (Compatibility + Fairness variance bonus - Invalid penalty)",
     "Tại sao Action Masking bắt buộc? Trọng số fairness_weight ảnh hưởng hội tụ ra sao?",
     "Env pass `check_env` của Gymnasium; MaskablePPO chạy được smoke test 10,000 steps; Unit tests pass 100%", "Chưa bắt đầu"),
    ("Tuần 4", "12/10 - 18/10/2026", "Bước 6: Multi-Algorithm Training & Hyperparameter Sweep",
     "Huấn luyện đa thuật toán: Maskable PPO, DQN, QR-DQN, A2C; Milestones 200k, 500k, 1M, 2M steps; Checkpoint logging",
     "Động học học tập của từng họ thuật toán? Tốc độ hội tụ vs hiện tượng policy overfitting?",
     "Tạo đủ checkpoint 12 runs (4 models x 3 milestones) và ghi JSON kết quả", "Chưa bắt đầu"),
    ("Tuần 5", "19/10 - 25/10/2026", "Bước 7 Part 1: Comprehensive Benchmark & Statistical Evals",
     "Benchmark 5 seeds đối sánh 8 thuật toán (Random, Greedy, SPA, Hungarian, PPO, DQN, A2C, QR-DQN); T-test thống kê",
     "PPO có vượt qua Greedy/SPA? Quota violations của unmasked DQN là bao nhiêu?",
     "Báo cáo mean ± std; PPO đạt 0 invalid proposals và >= 88-92% optimal score; p < 0.05", "Chưa bắt đầu"),
    ("Tuần 6", "26/10 - 01/11/2026", "Bước 7 Part 2: Lifecycle V2-V3, Promotion Gate & Web API",
     "Mô phỏng Lifecycle V2 (Preference modeling) & V3 (Online streaming arrival); Promotion gate; FastAPI & Dashboard SPA",
     "Khi nào promote PPO lên production? Trong bài toán streaming RL vượt Hungarian như thế nào?",
     "Dashboard hiển thị trực quan 5 sơ đồ IEEE 300 DPI và cho phép chạy matching tương tác", "Chưa bắt đầu"),
    ("Tuần 7", "02/11 - 08/11/2026", "Khai phá kết quả & Soạn thảo Khóa luận tốt nghiệp",
     "Viết toàn bộ Chương 1 đến Chương 12 bản thảo KLTN; Xuất đồ thị chuẩn IEEE/ACM 300 DPI; Soạn bảng biểu phụ lục",
     "Các luận điểm bảo vệ tính mới của đề tài? Phân tích tại sao Hungarian là upper bound batch?",
     "Hoàn thành 100% bản thảo luận văn (.docx / LaTeX / PDF) để GVHD duyệt lần 1", "Chưa bắt đầu"),
    ("Tuần 8", "09/11 - 15/11/2026", "Phản biện GVHD, Sửa chữa bản thảo & Nộp KLTN (DL 15/11)",
     "Tiếp thu góp ý của GVHD; Hoàn thiện slide thuyết trình PowerPoint; Diễn tập thử demo thuyết trình 15 phút; Đóng gói nộp KLTN",
     "Trả lời câu hỏi phản biện của hội đồng: tính ứng dụng thực tế và khả năng scale?",
     "Nộp bản cứng và file mềm KLTN trước 23:59 ngày 15/11/2026; Sẵn sàng bảo vệ đạt điểm A/A+", "Chưa bắt đầu"),
]

STEPS_7_DATA = [
    ("Bước 1", "Problem Formulation & Framing\n(Xác định & Mô hình hóa bài toán)",
     "Chuyển đổi bài toán phân công sang Ra quyết định Tuần tự Markov (MDP) có ràng buộc dung lượng cứng (Hard Quota)",
     "Quy chế phân công KLTN FIT NEU; Quota từng GV; Workload và cân bằng tải giữa các bộ môn",
     "MDP (S, A, P, R, gamma); Phân tích lý thuyết vì sao Multi-turn MDP khác với Hồi quy Supervised 1 bước",
     "docs/rl_algorithm_design.md\nSơ đồ MDP Flow (figure5_rl_mdp_flow.png)",
     "Định nghĩa toán học chặt chẽ; Trạng thái S bao quát đủ thông tin tài nguyên động; Action Masking xác định rõ", "Tuần 1"),

    ("Bước 2", "Data Ingestion, Cleaning & Provenance\n(Thu thập, Làm sạch & Quản trị nguồn gốc)",
     "Thu thập và làm sạch tái lập được dữ liệu luận văn và hồ sơ giảng viên, chống rò rỉ dữ liệu (data leakage)",
     "File PDF/DOCX luận văn các năm trước; Trang web hồ sơ GV FIT NEU; Khung CTĐT 5 ngành",
     "PDF text extraction; Gemini OCR/LLM extractor; Crawler hồ sơ GV; Name normalization; Identity mapping; Quality Report",
     "data/curated/theses.csv (198 bài)\ndata/curated/advisors.csv (39 GV)\ndata/curated/quality_report.json",
     "Zero unmatched rows; Zero duplicate students across splits; 100% provenance audit log; Raw data bất biến", "Tuần 1 - Tuần 2"),

    ("Bước 3", "Feature Engineering & Compatibility Representation\n(Kỹ thuật Đặc trưng & Biểu diễn Tương thích)",
     "Chuyển đổi văn bản phi cấu trúc thành không gian vector số học để tính độ tương đồng chuyên môn",
     "Cột văn bản từ theses.csv và advisors.csv; Từ khóa kỹ năng, framework, ngôn ngữ lập trình",
     "1. TF-IDF Vectorizer (ngram 1-2), fit CHỈ TRÊN TRAIN;\n2. Multilingual Sentence Transformers;\n3. Ma trận Cosine Similarity (N x M)",
     "Ma trận Compatibility (N, M);\nVectorizer pickle / Dense vector caches;\nDistribution analysis charts",
     "Zero leakage từ test vào từ điển train; Phân phối cosine similarity có độ phân hóa tốt", "Tuần 2"),

    ("Bước 4", "Environment Modeling & State Dynamics\n(Xây dựng Môi trường Mô phỏng & Động học Trạng thái)",
     "Mô phỏng quy trình phân bổ: khi 1 SV được gán, quota GV giảm dần và tải hệ thống biến đổi",
     "Ma trận Compatibility; Vector hạn mức chỉ tiêu ban đầu của 39 giảng viên",
     "GymMatchingEnv (Gymnasium Env);\nState Observation: [compatibility (M), remaining_capacity_ratio (M), current_load_ratio (M)] -> Size 3*M;\nAction Masking",
     "src/environment/gym_matching_env.py\nsrc/environment/matching_core.py\nUnit tests kiểm thử môi trường",
     "Vượt qua kiểm tra chuẩn Gymnasium check_env; 100% chặn được hành động chọn GV đã hết quota; Reset deterministic", "Tuần 3"),

    ("Bước 5", "Reward & Loss Function Engineering\n(Thiết kế Hàm Thưởng & Hàm Mất Mát)",
     "Định hình hành vi của Agent qua hàm thưởng đa mục tiêu kết hợp chuyên môn, công bằng tải và phạt vi phạm",
     "State observation, action taken, capacity remaining, historical load distribution",
     "Reward: r = w_comp * comp + w_fair * (var_before - var_after) - w_pen * invalid_flag;\nLoss PPO: Clipped Surrogate Objective Loss;\nLoss DQN: Temporal Difference (TD) Huber Loss",
     "src/environment/reward_functions.py\nLoss/Reward mathematical specs document",
     "Reward có tính Markov, không gây reward hacking; Agent học cân bằng giữa chuyên môn tối đa và chia đều tải GV", "Tuần 1 & Tuần 3"),

    ("Bước 6", "Offline Training & Multi-Model Comparative Benchmarking\n(Huấn luyện Đa thuật toán & Thí nghiệm Đối chuẩn)",
     "Huấn luyện các mô hình RL theo milestone và đánh giá toàn diện so với các thuật toán phân bổ kinh điển",
     "Dataset split theo thời gian (Train: pre-2025 + 75% 2025; Val: 12.5% 2025; Test: 12.5% 2025); 5 Seeds độc lập",
     "Họ Policy-based: Maskable PPO;\nHọ Value-based: DQN, QR-DQN;\nHọ Actor-Critic: A2C;\nBaselines: Random, Greedy, Gale-Shapley SPA, Exact Hungarian",
     "12 Checkpoints .zip;\noutputs/results/*.json;\nBảng tổng hợp Mean ± Std qua 5 seeds",
     "PPO đạt 0 invalid proposals; Không vượt quota bất kỳ GV nào; Đạt >= 88-92% cận trên Hungarian; Chạy < 100ms", "Tuần 4 - Tuần 5"),

    ("Bước 7", "Model Governance, Lifecycle V1-V3, Deployment & Continuous Feedback\n(Quản trị, Vòng đời Sản phẩm & Ứng dụng)",
     "Đóng gói mô hình thành hệ thống hỗ trợ ra quyết định thời gian thực, có cổng thăng hạng (Promotion Gate) và Human-in-the-loop",
     "Checkpoint tối ưu vượt qua Gate; Ràng buộc nghiệp vụ thực tế; Yêu cầu giao diện người dùng",
     "Model Registry & Manifest (SHA256, Git commit);\nPromotion Gate Logic (select_engine);\nFastAPI Backend & Interactive SPA Dashboard;\nLifecycle V2 & V3",
     "KE_HOACH_CHECKLIST_KLTN_RL_MATCHING.xlsx\nFastAPI Swagger UI (/docs)\nDashboard Web SPA\n5 Biểu đồ công bố IEEE 300 DPI",
     "Khởi chạy hệ thống hoàn chỉnh với 1 lệnh; Giao diện trực quan, cho phép hội đồng kiểm tra và override; Sẵn sàng bảo vệ", "Tuần 6 - Tuần 8"),
]
QA_WEEK1_DATA_PART1 = [
    ("Câu 1", "Giảng viên nhận features gì? (Advisor Feature Representation)",
     "Đặc trưng Hồ sơ Tĩnh (Static Profile)",
     "1. primary_field: Chuyên ngành chính (AI, Web, Data, Mobile, Security...)\n2. skill_text & skill_count: Tập từ khóa kỹ năng từ môn học & bài báo\n3. publication_evidence_count: Số bài báo khoa học làm minh chứng năng lực\n4. academic_title: Học hàm/học vị (GS, PGS, TS, ThS)\n5. text_profile: Ghép các trường để nhúng vector TF-IDF/Dense",
     "Xác định năng lực chuyên môn và hướng nghiên cứu thực tế của từng GV",
     "data/curated/advisors.csv; advisors.shape=(M, F_gv)"),

    ("Câu 1", "Giảng viên nhận features gì? (Advisor Feature Representation)",
     "Đặc trưng Ràng buộc & Tải Động (Dynamic Capacity & Load)",
     "1. capacity_max (C_j): Hạn mức tối đa số SV hướng dẫn (ceil(N/M))\n2. current_load (L_{j, t}): Số sinh viên đã gán cho GV j tại bước t\n3. remaining_capacity_ratio: (C_j - L_{j, t}) / C_j in [0.0, 1.0]\n4. load_ratio: L_{j, t} / C_j in [0.0, 1.0]",
     "Cung cấp thông tin tài nguyên tức thời để Policy điều phối cân bằng tải",
     "Tính động trong GymMatchingEnv.observation() ở mỗi bước step(action)"),

    ("Câu 2", "Sinh viên nhận features gì? (Student Feature Representation)",
     "Đặc trưng Đề tài & Hồ sơ Học tập (Thesis & Academic Features)",
     "1. thesis_title: Tên đề tài khóa luận (văn bản tiếng Việt)\n2. field_category: Lĩnh vực đề tài (Web, Mobile, AI, IoT...)\n3. Tech stack: web_languages, frameworks (frontend, backend, AI), database, data_tools\n4. research_methods: Phương pháp nghiên cứu (UML, Thực nghiệm, Toán...)\n5. primary_role & secondary_roles: Phân loại vai trò kỹ thuật chính của SV",
     "Đại diện đầy đủ cho nội dung, công nghệ và yêu cầu chuyên môn của khóa luận",
     "data/curated/theses.csv; theses.shape=(N, F_sv); TF-IDF / Embedding"),

    ("Câu 2", "Sinh viên nhận features gì? (Student Feature Representation)",
     "Vector Quan sát Tổng hợp Đưa vào Mô hình RL (State Observation Vector)",
     "Tại mỗi bước t khi xét SV i = s_t, vector Observation s_t có kích thước 3 * M:\n1. Compatibility Scores [M chiều]: [sim(i, 1), sim(i, 2), ..., sim(i, M)]\n2. Remaining Capacity Ratios [M chiều]: [(C_1 - L_1)/C_1, ..., (C_M - L_M)/C_M]\n3. Current Load Ratios [M chiều]: [L_1/C_1, ..., L_M/C_M]\nTổng kích thước quan sát: Dim(S) = 3 * M (với M=39 giảng viên -> 117 chiều)",
     "Đưa độ phù hợp chuyên môn của SV hiện tại và tải của toàn bộ GV vào Neural Policy",
     "Gymnasium Observation: Box(-1.0, 1.0, shape=(3*M,), dtype=np.float32)"),

    ("Câu 3", "Hàm Reward được thiết kế như thế nào? (Reward Formulation)",
     "Công thức Hàm Thưởng Đa Mục tiêu",
     "Hàm reward r_t tại bước t khi gán SV i cho GV a_t:\nr_t = w_{comp} * comp(i, a_t) + w_{fair} * (Var_{before} - Var_{after}) - w_{pen} * I_{invalid}\nTrong đó:\n- comp(i, a_t) in [0, 1]: Cosine similarity giữa SV i và GV a_t.\n- Var: Phương sai tải chuẩn hóa toàn bộ M GV: Var = (1/M) * sum((L_j / C_j - mean_load)^2).\n  Nếu action làm giảm phương sai tải -> (Var_{before} - Var_{after}) > 0 -> Thưởng cân bằng tải!\n- w_{fair} = 0.15; w_{pen} = 2.0 (phạt nếu vi phạm chọn GV hết quota khi không mask).",
     "Định hướng Agent tối đa chuyên môn và tự động chia đều tải cho các GV",
     "MatchingEnv.step() trong src/environment/matching_core.py"),

    ("Câu 3", "Hàm Loss được thiết kế như thế nào? (Loss Formulation)",
     "Loss của Maskable PPO & Value-based (DQN/QR-DQN)",
     "1. PPO: L^{PPO}(theta) = E_t [ L^{CLIP}(theta) - c_1 * L^{VF}(theta) + c_2 * S[pi_theta](s_t) ]\n  với L^{CLIP}(theta) = min(r_t(theta)*A_t, clip(r_t(theta), 1-eps, 1+eps)*A_t).\n  Action Masking áp đặt p(a | s) = 0 cho action không hợp lệ trước Softmax!\n2. DQN: L^{DQN}(theta) = E [ ( r + gamma * max_{a'} Q(s', a'; theta^-) - Q(s, a; theta) )^2 ].\n3. QR-DQN: Quantile Huber Loss trên 32 quantiles ước lượng phân phối phần thưởng.",
     "Tối ưu policy an toàn, hội tụ ổn định, đảm bảo 0 vi phạm quota",
     "sb3-contrib MaskablePPO & QRDQN; stable_baselines3 DQN"),
]

QA_WEEK1_DATA_PART2 = [
    ("Câu 4", "Đánh giá như thế nào, dựa trên cái gì? (Evaluation Methodology)",
     "Bộ 6 Thước đo Đánh giá & Giao thức Nghiêm ngặt",
     "1. Mean Compatibility: Trung bình điểm tương thích toàn cohort: (1/N) * sum(comp(i, a_i))\n2. Quota Violations (Ràng buộc cứng): Tổng số SV bị gán vượt chỉ tiêu -> BẮT BUỘC = 0\n3. Invalid Proposals: Số lần model đề xuất sai luật trước khi can thiệp -> BẮT BUỘC = 0 với PPO\n4. Load Variance: Phương sai tải giữa các GV -> Càng nhỏ càng công bằng\n5. Historical Top-1 Accuracy: Tỷ lệ trùng khớp phân công lịch sử\n6. Theoretical Optimality Ratio: Tỷ lệ so với Hungarian: Score_RL / Score_Hungarian * 100%\nGiao thức: Temporal Split (Train pre-2025+75% 2025; Val/Test 2025); 5 Seeds; t-test p < 0.05",
     "Đánh giá toàn diện chất lượng, ràng buộc kỹ thuật, tính công bằng và tính tối ưu",
     "src/rl/benchmark.py; outputs/results/benchmark_validation_5seeds.json"),

    ("Câu 5", "Các vòng đời V1, V2, V3... thiết kế thế nào? Tại sao 1 vòng nhầm sang hồi quy?",
     "Phân biệt Bản chất: Multi-turn MDP vs 1-Step Regression",
     "- HỒI QUY 1 BƯỚC (Supervised 1-Step):\n  Mỗi SV x_i được dự đoán độc lập: y_hat = f(x_i). Quyết định gán SV 1 KHÔNG LÀM THAY ĐỔI không gian lựa chọn của SV 2. Không có biến động tài nguyên.\n- QUÁ TRÌNH RA QUYẾT ĐỊNH MARKOV TUẦN TỰ (Multi-turn MDP):\n  Khi gán SV s_1 cho GV A, hạn mức GV A giảm đi 1. Trạng thái môi trường S_{t+1} BỊ BIẾN ĐỔI bởi hành động a_t! Khi GV A hết quota, action chọn A trở thành BẤT HỢP LỆ. Quyết định hiện tại ảnh hưởng trực tiếp đến không gian hành động và phần thưởng tương lai. Đây chính là MDP nhiều bước!",
     "Cơ sở lý luận bảo vệ việc áp dụng RL thay vì Hồi quy đơn thuần trước hội đồng",
     "Minh chứng bằng vector remaining_capacity biến đổi qua các bước t=1..N"),

    ("Câu 5", "Các vòng đời V1, V2, V3... thiết kế thế nào? Có bao nhiêu vòng?",
     "Thiết kế 4 Vòng đời Hệ thống (Lifecycles V1 -> V4)",
     "V1 (Foundational Offline RL): TF-IDF compatibility, cohort tĩnh, so sánh PPO vs DQN vs Hungarian.\nV2 (Semantic & Preference RL): Bổ sung nguyện vọng SV Top 3; Đổi sang Sentence Transformers.\nV3 (Online Streaming Sequential Arrival): SV đăng ký phân tán lệch thời gian (rolling window), cập nhật quota realtime. RL vượt trội Hungarian vì Hungarian không biết tương lai!\nV4 (Human-in-the-loop Continual Learning): Hội đồng duyệt/override -> Fine-tune policy từ feedback.",
     "Lộ trình tiến hóa từ nghiên cứu offline đến hệ thống phần mềm ứng dụng thực tiễn",
     "Dàn ý chương 10, 11; backend/ & src/simulator/"),

    ("Câu 6", "Accuracy dự định đạt bao nhiêu %, lấy gì để so sánh?",
     "Hệ thống Đối chuẩn & Mục tiêu Định lượng Từng Vòng",
     "ĐỐI CHUẨN SO SÁNH (Baselines):\n1. Random Allocation: Cận dưới tối thiểu (Mean Comp: ~0.018)\n2. Greedy Similarity: Cận tham lam cục bộ (Mean Comp: ~0.0618)\n3. Gale-Shapley SPA: Đối chuẩn bền vững 2 chiều (Mean Comp: ~0.0618)\n4. Exact Hungarian: CẬN TRÊN TOÀN CỤC (Theoretical Upper Bound 100%, Mean Comp: ~0.0656)\nMỤC TIÊU ACCURACY TỪNG VÒNG:\n- VÒNG 1: Quota Violations: 0% (100% hợp lệ); Optimality Ratio: PPO đạt 84.7% -> Tuning đạt 88-92% Hungarian; Historical Top-1: 25-35% (lịch sử chỉ là weak signal).\n- VÒNG 2: Optimality Ratio đạt 90-95% Hungarian; Top-3 Preference Satisfaction >= 85%.\n- VÒNG 3 (Online Streaming): PPO vượt Greedy từ 12-18% và vượt Static Hungarian từ 8-14%!",
     "Tạo lập hệ quy chiếu số liệu minh bạch và mục tiêu định lượng có thể kiểm chứng",
     "Bảng kết quả Chapter 8; outputs/results/"),
]

QA_WEEK1_DATA = QA_WEEK1_DATA_PART1 + QA_WEEK1_DATA_PART2

ALGO_COMP_DATA = [
    ("Baseline Ngẫu nhiên", "Random", "Chọn ngẫu nhiên 1 GV còn dung lượng trống cho từng SV", "Có (qua lọc slot)", "Rất thấp (Mean Comp: 0.018)", "Có", "O(N)", "Mean Comp: 0.018001\nViolations: 0\nLoad Var: 0.2498", "Cận dưới tối thiểu (Floor Baseline)"),
    ("Heuristic Tham lam", "Greedy Similarity", "Gán SV cho GV hợp lệ có điểm tương thích cao nhất tại thời điểm xét", "Có (qua lọc slot)", "Cục bộ (Mean Comp: 0.0618)", "Có (tối ưu cục bộ)", "O(N * M)", "Mean Comp: 0.061767\nViolations: 0\nLoad Var: 0.2498", "Heuristic cục bộ phổ biến trong thực tế"),
    ("Ghép đôi Kinh điển", "Gale-Shapley (SPA)", "Sinh viên đề xuất tuần tự theo bảng ưu tiên; GV nhận tạm và từ chối nếu quá tải", "Có (theo hạn mức GV)", "Khá cao (Mean Comp: 0.0618)", "Kém (cần bảng ưu tiên trước)", "O(N * M)", "Mean Comp: 0.061788\nViolations: 0\nLoad Var: 0.2498", "Đối chuẩn tính ổn định (Two-sided Stability)"),
    ("Quy hoạch Toán học", "Exact Hungarian (Munkres)", "Quy hoạch nguyên tuyến tính cực tiểu hóa chi phí (Min-cost Max-flow) trên ma trận bù", "Có (mở rộng slot GV)", "TỐI ƯU TOÀN CỤC (Global Optimum)", "KHÔNG THỂ (Bất khả thi khi SV đến ngẫu nhiên)", "O(N^3)", "Mean Comp: 0.065601\nViolations: 0\nLoad Var: 0.2498", "CẬN TRÊN LÝ THUYẾT (Theoretical Upper Bound 100%) & Production Batch Engine"),
    ("RL (Policy-based)", "Maskable PPO (Đề xuất chính)", "Policy Gradient với Clipped Surrogate Loss kết hợp Action Masking triệt tiêu hành động vi phạm", "TUYỆT ĐỐI (0 vi phạm qua ActionMaskEnv)", "Rất cao (Đạt 84.7% - 92% Hungarian)", "XUẤT SẮC (Tối ưu hóa hành động theo thời gian thực)", "Inference O(M)\nTrain O(T)", "Mean Comp: 0.055579 (1M steps)\nInvalid: 0 (0%)\nViolations: 0", "MÔ HÌNH RL CHÍNH CỦA ĐỀ TÀI (Được đề xuất cho Streaming)"),
    ("RL (Value-based)", "Standard DQN", "Học hàm giá trị Q(s,a) qua mạng Deep Q-Network và Experience Replay, không có mặt nạ", "Kém (Thường xuyên chọn GV đã hết quota)", "Trung bình (Bị phạt nặng)", "Khá (cần fallback can thiệp)", "Inference O(M)\nTrain O(T)", "Mean Comp: 0.048941*\nInvalid: 13/20 (65% lỗi!)\nViolations: 0 (sau fix)", "MÔ HÌNH ĐỐI CHỨNG (Chứng minh Action Masking bắt buộc)"),
    ("RL (Distributional)", "QR-DQN (Quantile Regression)", "Ước lượng phân phối xác suất đầy đủ của phần thưởng qua 32 quantile regressions", "Kém nếu không mask", "Khá cao", "Khá", "Inference O(M * Q)", "Mean Comp: 0.064199*\nInvalid: 17/20 (85% lỗi!)\nViolations: 0 (sau fix)", "Mô hình nâng cao đối chứng học độ bất định"),
    ("RL (Actor-Critic)", "A2C (Advantage Actor-Critic)", "Kiến trúc Actor-Critic đồng bộ cập nhật policy dựa trên hàm lợi thế Advantage A(s,a)", "Kém nếu không mask", "Khá cao", "Khá", "Inference O(M)", "Mean Comp: 0.063387*\nInvalid: 19/20 (95% lỗi!)\nViolations: 0 (sau fix)", "Mô hình đối chứng kiến trúc Actor-Critic cổ điển"),
]

TASKS_W1_W2 = [
    # TUẦN 1: FOUNDATION & 6 CORE QUESTIONS (21/09 - 27/09)
    ("Bước 1: Problem Formulation", "Thiết lập môi trường làm việc, đọc và phân tích toàn diện repo, đối soát dữ liệu hiện có",
     "Hiểu rõ toàn bộ mã nguồn, data/curated, docs, và đề cương KLTN", "Ghi chú kiến trúc hệ thống", "git status; python -m pytest", "Hoàng Văn Nam", "Hoàn thành", "Kiểm tra phiên bản Python 3.12 & dependencies"),
    ("Bước 1: Problem Formulation", "Xây dựng định nghĩa toán học chi tiết cho bài toán Phân công Sinh viên - Giảng viên (MDP)",
     "Xác định không gian Trạng thái S, Hành động A, Chuyển trạng thái P, Thưởng R, Chiết khấu gamma", "docs/rl_formulation_math.md", "python -c \"import src.environment\"", "Hoàng Văn Nam", "Hoàn thành", "Phân biệt rõ bài toán offline batch vs online streaming"),
    ("Bước 1 & 5: Feature & Reward", "Thiết kế và mô tả chi tiết: Giảng viên nhận features gì? Sinh viên nhận features gì?",
     "Hoàn thiện danh sách đặc trưng đầu vào cho cả 2 phía (GV và SV) dạng bảng tường minh", "docs/features_specification.md", "python -m src.data_pipeline.split_dataset", "Hoàng Văn Nam", "Đang thực hiện", "Đảm bảo không rò rỉ thông tin trước thời điểm ghép cặp"),
    ("Bước 5: Loss & Reward", "Thiết kế toán học hàm Loss (PPO, DQN, A2C) và hàm Reward đa mục tiêu (Fairness + Comp - Penalty)",
     "Công thức toán học giải thích chi tiết cơ chế cân bằng tải load variance reduction", "docs/loss_reward_formulation.md", "python -c \"from src.environment.matching_core import MatchingEnv\"", "Hoàng Văn Nam", "Đang thực hiện", "Hàm reward phải có tính gradient hướng dẫn rõ ràng"),
    ("Bước 1 & 7: Lifecycle & Evaluation", "Thiết kế các vòng đời V1, V2, V3...; Lý giải vì sao multi-turn MDP khác với hồi quy 1 vòng",
     "Làm rõ tính biến động của state (dynamic capacity constraint) khi từng SV được gán", "docs/lifecycle_and_mdp_stages.md", "python -m src.rl.benchmark --help", "Hoàng Văn Nam", "Chưa bắt đầu", "Nhấn mạnh luận điểm bảo vệ trước hội đồng"),
    ("Bước 7: Benchmark Metrics", "Xác định mục tiêu accuracy từng vòng (Historical Top-1 vs Optimality Ratio vs Constraint satisfaction)",
     "Thiết lập thang đo đối chuẩn: so sánh với Random, Greedy, Gale-Shapley SPA, Hungarian", "docs/target_metrics_baselines.md", "python scripts/run_checkpoint_benchmarks.py", "Hoàng Văn Nam", "Chưa bắt đầu", "Hungarian là theoretical upper bound cho batch matching"),
    ("Tuần 1: Review & Tổng kết", "Rà soát toàn bộ tài liệu Tuần 1, đóng gói báo cáo trả lời 6 câu hỏi lớn cho GVHD",
     "Tài liệu hoàn chỉnh sẵn sàng gửi GVHD duyệt định hướng nghiên cứu", "baocao/tuan1_tra_loi_cau_hoi.pdf", "git commit -m \"Complete Week 1 deliverables\"", "Hoàng Văn Nam", "Chưa bắt đầu", "Xin feedback sớm từ Thầy/Cô hướng dẫn"),

    # TUẦN 2: DATA CLEANING & FEATURE PIPELINE (28/09 - 04/10)
    ("Bước 2: Data Cleaning", "Kiểm tra và audit toàn diện file data/curated/theses.csv (198 khóa luận) và advisors.csv (39 GV)",
     "Xác định tỷ lệ thiếu (null rate), lỗi chính tả tiếng Việt, chuẩn hóa tên GV và mã đề tài", "data/curated/quality_report_v2.json", "python -m src.data_pipeline.clean_processed_data", "Hoàng Văn Nam", "Chưa bắt đầu", "Bảo đảm provenance, không ghi đè raw data"),
    ("Bước 2: Data Cleaning", "Xử lý dữ liệu văn bản tiếng Việt: tách từ pyvi/underthesea, loại bỏ stop words chuyên ngành",
     "Làm sạch cột thesis_title, specialty_field, skill_evidence của giảng viên", "src/nlp/vietnamese_cleaner.py", "pytest tests/test_nlp.py", "Hoàng Văn Nam", "Chưa bắt đầu", "Giữ lại các thuật ngữ công nghệ tiếng Anh chuẩn"),
    ("Bước 3: Feature Engineering", "Xây dựng TF-IDF Vectorizer chuẩn hóa với n-gram (1, 2), fit duy nhất trên tập Train",
     "Chống rò rỉ dữ liệu (data leakage) giữa tập Train và Hold-out Test/Val", "src/environment/matching_core.py", "python -m src.rl.benchmark --seed 42", "Hoàng Văn Nam", "Chưa bắt đầu", "Kiểm tra vocab không chứa từ vựng riêng của Test set"),
    ("Bước 3: Feature Engineering", "Tích hợp mô hình Sentence-Transformers tiếng Việt đa ngữ (paraphrase-multilingual-mpnet-base-v2)",
     "Tạo dense vector embeddings 768 chiều cho sinh viên và hồ sơ giảng viên", "data/embeddings/thesis_embeddings.npy", "python -c \"import sentence_transformers\"", "Hoàng Văn Nam", "Chưa bắt đầu", "Cache vector vào ổ đĩa để tăng tốc huấn luyện"),
    ("Bước 3: Feature Engineering", "Xây dựng ma trận Compatibility đối chuẩn (Cosine Similarity trên TF-IDF và Dense Embedding)",
     "Ma trận kích thước N x M có phân phối điểm chuẩn hóa trong khoảng [0, 1]", "eval/compatibility_analysis.png", "python scripts/validate_data.py", "Hoàng Văn Nam", "Chưa bắt đầu", "So sánh độ phân hóa (sparsity vs density) giữa 2 cách biểu diễn"),
    ("Bước 2 & 3: Data Contract", "Thiết lập Data Contract tự động kiểm tra tính hợp lệ của schema trước mỗi lần train",
     "Assert không có NaN, dung lượng đủ cho cohort, student_id là duy nhất trong split", "src/models/data_contract.py", "pytest tests/test_data_contract.py", "Hoàng Văn Nam", "Chưa bắt đầu", "Fail-fast nếu phát hiện dữ liệu lỗi"),
    ("Tuần 2: Review & Tổng kết", "Đánh giá chất lượng pipeline tiền xử lý dữ liệu và ma trận độ tương thích",
     "Báo cáo thống kê độ tương thích trung bình theo từng chuyên ngành (AI, Web, Mobile...)", "docs/week2_data_feature_report.md", "git commit -m \"Finalize Data Pipeline & Features\"", "Hoàng Văn Nam", "Chưa bắt đầu", "Chuẩn bị môi trường RL cho Tuần 3"),
]

TASKS_W3_W4 = [
    # TUẦN 3: ENVIRONMENT & REWARD/LOSS ENGINEERING (05/10 - 11/10)
    ("Bước 4: RL Environment", "Tái cấu trúc GymMatchingEnv tuân thủ chuẩn Gymnasium API mới nhất",
     "Observation space: Box(-1.0, 1.0, shape=(3*M,)), Action space: Discrete(M)", "src/environment/gym_matching_env.py", "python -c \"from src.environment.gym_matching_env import GymMatchingEnv\"", "Hoàng Văn Nam", "Chưa bắt đầu", "Kiểm tra tính tương thích với Stable-Baselines3"),
    ("Bước 4: RL Environment", "Hiện thực cơ chế Action Masking với sb3-contrib ActionMaskEnv",
     "Triệt tiêu hoàn toàn khả năng Agent chọn giảng viên đã đầy quota ở mỗi bước t", "src/environment/action_masking.py", "pytest tests/test_action_masking.py", "Hoàng Văn Nam", "Chưa bắt đầu", "Action mask vector boolean shape (M,) cập nhật liên tục"),
    ("Bước 5: Reward Engineering", "Hiện thực hàm thưởng chi tiết: r = comp + w_fair * delta_var - penalty",
     "Thử nghiệm các giá trị trọng số w_fair in [0.05, 0.15, 0.30] để tìm điểm cân bằng Pareto", "src/environment/reward_functions.py", "python -m pytest tests/test_reward.py", "Hoàng Văn Nam", "Chưa bắt đầu", "Phần thưởng delta_var phải dương khi tải đồng đều hơn"),
    ("Bước 5: Reward Engineering", "Tích hợp thành phần thưởng nguyện vọng sinh viên (Preference bonus) và vai trò (Role bonus)",
     "Tăng reward khi SV được ghép đúng nguyện vọng 1 hoặc đúng chuyên ngành cốt lõi", "src/environment/extended_rewards.py", "python scripts/validate_rewards.py", "Hoàng Văn Nam", "Chưa bắt đầu", "Giữ tham số cấu hình linh hoạt qua configs/settings.py"),
    ("Bước 4 & 5: Test Environment", "Viết bộ Unit test và Integration test toàn diện cho GymMatchingEnv",
     "Kiểm thử reset, step, termination, truncation, load decrement, invalid handling", "tests/test_gym_matching_env.py", "python -m pytest tests/ -v", "Hoàng Văn Nam", "Chưa bắt đầu", "Đảm bảo code coverage cho module environment >= 90%"),
    ("Bước 4: Simulator CLI", "Hoàn thiện CLI mô phỏng phân bổ theo từng bước (Step-by-step matching simulator)",
     "In ra terminal visual progress khi từng SV được gán vào GV, hiển thị quota còn lại", "scripts/simulate_matching.py", "python scripts/simulate_matching.py --steps 5", "Hoàng Văn Nam", "Chưa bắt đầu", "Hỗ trợ visual phục vụ giải thích cho GVHD"),
    ("Tuần 3: Review & Tổng kết", "Chạy Smoke test huấn luyện Maskable PPO trên 20,000 steps để kiểm tra tính ổn định",
     "Xác nhận policy loss giảm, reward hội tụ, không phát sinh lỗi bộ nhớ hay crash", "outputs/smoke_test_ppo.json", "python -m src.rl.train --algorithm ppo --timesteps 20000", "Hoàng Văn Nam", "Chưa bắt đầu", "Sẵn sàng tài nguyên GPU/CPU cho huấn luyện lớn"),

    # TUẦN 4: MULTI-ALGORITHM TRAINING SUITE (12/10 - 18/10)
    ("Bước 6: RL Training", "Thiết lập kịch bản huấn luyện tích lũy theo milestone: 200k -> 500k -> 1M -> 2M steps",
     "Tiết kiệm tài nguyên tính toán bằng cách train tiếp từ checkpoint trước đó", "src/rl/train.py", "python -m src.rl.train --help", "Hoàng Văn Nam", "Chưa bắt đầu", "Sử dụng callback lưu checkpoint tốt nhất theo val reward"),
    ("Bước 6: RL Training", "Huấn luyện chuyên sâu mô hình Maskable PPO với 3 random seeds (42, 123, 999)",
     "Thu được các checkpoint ppo_seed{seed}_steps{milestone}.zip", "outputs/models/ppo_seed42_steps1000000.zip", "python -m src.rl.train --algorithm ppo --timesteps 1000000 --seed 42", "Hoàng Văn Nam", "Chưa bắt đầu", "Theo dõi TensorBoard log: value_loss, policy_loss, entropy"),
    ("Bước 6: RL Training", "Huấn luyện mô hình đối chứng DQN và Double DQN trên cùng môi trường",
     "Ghi nhận số lượng Invalid Proposals khi không có Action Masking", "outputs/models/dqn_seed42_steps1000000.zip", "python -m src.rl.train --algorithm dqn --timesteps 1000000 --seed 42", "Hoàng Văn Nam", "Chưa bắt đầu", "Chứng minh nhược điểm của DQN unmasked trong ràng buộc cứng"),
    ("Bước 6: RL Training", "Huấn luyện mô hình QR-DQN (Quantile Regression DQN) đối chứng học phân phối phần thưởng",
     "Đánh giá tính ổn định của distributional RL so với standard DQN", "outputs/models/qrdqn_seed42_steps1000000.zip", "python -m src.rl.train --algorithm qrdqn --timesteps 1000000 --seed 42", "Hoàng Văn Nam", "Chưa bắt đầu", "sb3-contrib QRDQN với 32 quantiles"),
    ("Bước 6: RL Training", "Huấn luyện mô hình A2C (Advantage Actor-Critic) đối chứng mô hình Actor-Critic đồng bộ",
     "So sánh tốc độ cập nhật gradient và độ ổn định phương sai với PPO", "outputs/models/a2c_seed42_steps1000000.zip", "python -m src.rl.train --algorithm a2c --timesteps 1000000 --seed 42", "Hoàng Văn Nam", "Chưa bắt đầu", "A2C n_steps=256"),
    ("Bước 6: Hyperparameter Tuning", "Sweep siêu tham số cho Maskable PPO: learning_rate (1e-4, 3e-4), ent_coef, clip_range",
     "Tìm bộ hyperparameter tối ưu cho bài toán Student-Advisor Matching", "configs/ppo_best_hyperparams.json", "python scripts/tune_hyperparams.py", "Hoàng Văn Nam", "Chưa bắt đầu", "Chọn checkpoint có validation compatibility cao nhất"),
    ("Tuần 4: Review & Tổng kết", "Kiểm tra tính toàn vẹn của tất cả 12 checkpoints đã lưu và manifest provenance",
     "Toàn bộ checkpoint load được không lỗi, SHA256 checksum được ghi nhận", "outputs/results/training_manifest_w4.json", "python scripts/release_model.py --verify", "Hoàng Văn Nam", "Chưa bắt đầu", "Sao lưu dữ liệu checkpoint lên Google Drive / External Drive"),
]

TASKS_W5_W6 = [
    # TUẦN 5: COMPREHENSIVE BENCHMARK & EVALUATION (19/10 - 25/10)
    ("Bước 7: Evaluation", "Triển khai bộ giải thuật Baseline cổ điển: Random, Greedy Similarity",
     "Thiết lập cận dưới (Random) và cận tham lam cục bộ (Greedy)", "src/baselines/classical.py", "python -m src.rl.benchmark --strategy greedy", "Hoàng Văn Nam", "Chưa bắt đầu", "Đảm bảo Greedy tuân thủ quota chính xác"),
    ("Bước 7: Evaluation", "Triển khai giải thuật Gale-Shapley SPA (Student-Project Allocation with Capacities)",
     "Đánh giá tính ổn định hai chiều (Two-sided matching stability) và độ hài lòng", "src/baselines/spa.py", "python -m src.rl.benchmark --strategy spa", "Hoàng Văn Nam", "Chưa bắt đầu", "Tối ưu hóa thứ tự đề xuất từ phía sinh viên"),
    ("Bước 7: Evaluation", "Triển khai bộ giải Exact Hungarian (Linear Sum Assignment) làm Theoretical Upper Bound",
     "Tính toán phân bổ toàn cục tối ưu tuyệt đối cho bài toán batch matching", "src/baselines/exact_hungarian.py", "python -m src.rl.benchmark --strategy exact", "Hoàng Văn Nam", "Chưa bắt đầu", "Ghi nhận score của Hungarian làm mốc 100% chuẩn"),
    ("Bước 7: Evaluation", "Chạy Benchmark đa thuật toán toàn diện trên 5 Seeds ngẫu nhiên trên tập Validation",
     "So sánh 8 thuật toán: Random, Greedy, SPA, Hungarian, PPO, DQN, A2C, QR-DQN", "outputs/results/benchmark_validation_5seeds.json", "python scripts/run_checkpoint_benchmarks.py --split validation", "Hoàng Văn Nam", "Chưa bắt đầu", "Tính giá trị trung bình (mean) và độ lệch chuẩn (std)"),
    ("Bước 7: Evaluation", "Phân tích thống kê và kiểm định giả thuyết (T-test, Wilcoxon signed-rank test)",
     "Chứng minh PPO vượt trội có ý nghĩa thống kê (p < 0.05) so với Random, Greedy và DQN", "eval/statistical_significance_report.md", "python eval/run_statistical_tests.py", "Hoàng Văn Nam", "Chưa bắt đầu", "Báo cáo p-value và effect size"),
    ("Bước 7: Evaluation", "Đánh giá Ablation Studies: Ảnh hưởng của Action Masking, Fairness Bonus và Text Representation",
     "Làm rõ đóng góp của từng thành phần trong hệ thống RL", "outputs/results/ablation_study_results.json", "python scripts/run_ablation.py", "Hoàng Văn Nam", "Chưa bắt đầu", "Biểu đồ cột so sánh trực quan từng biến thể"),
    ("Tuần 5: Review & Tổng kết", "Chạy đánh giá duy nhất một lần (Final Hold-out Evaluation) trên tập Test set",
     "Bảo đảm tính khách quan tuyệt đối của kết quả nghiên cứu học thuật", "outputs/results/final_test_benchmark.json", "python scripts/run_checkpoint_benchmarks.py --split test", "Hoàng Văn Nam", "Chưa bắt đầu", "Khóa cố định tập test, không tuning thêm"),

    # TUẦN 6: LIFECYCLE V2-V3, PROMOTION GATE & WEB DASHBOARD (26/10 - 01/11)
    ("Bước 7: ML Lifecycle", "Hiện thực hoá bài toán Lifecycle V2: Phân bổ có kết hợp Nguyện vọng & Feedback lịch sử",
     "Tích hợp ma trận ưu tiên (Preference matrix) của sinh viên vào hàm mục tiêu", "src/rl/lifecycle_v2.py", "pytest tests/test_lifecycle_v2.py", "Hoàng Văn Nam", "Chưa bắt đầu", "So sánh độ thỏa mãn nguyện vọng Top-1, Top-3"),
    ("Bước 7: ML Lifecycle", "Hiện thực hoá bài toán Lifecycle V3: Mô phỏng phân công tuần tự thời gian thực (Online Streaming)",
     "Sinh viên đến ngẫu nhiên theo thời gian thực (Asynchronous student arrival)", "src/simulator/streaming_arrival.py", "python scripts/simulate_streaming.py", "Hoàng Văn Nam", "Chưa bắt đầu", "Chứng minh RL vượt trội Hungarian khi không biết trước tương lai"),
    ("Bước 7: Model Governance", "Hiện thực hoá Promotion Gate tự động: Luật lựa chọn Engine sản phẩm",
     "Chỉ promote PPO khi đạt 0 vi phạm quota, 0 invalid proposals và vượt baseline an toàn", "src/rl/promotion.py", "pytest tests/test_promotion.py", "Hoàng Văn Nam", "Chưa bắt đầu", "Ghi nhận Manifest và đóng gói Release"),
    ("Bước 7: Deployment & UI", "Hoàn thiện và kiểm thử toàn bộ Backend FastAPI (Endpoints matching, benchmark, recommendation)",
     "API phản hồi trong < 200ms cho bài toán phân bổ cả cohort", "backend/app/api/endpoints.py", "pytest tests/test_api.py", "Hoàng Văn Nam", "Chưa bắt đầu", "Tài liệu Swagger UI tự động tại /docs"),
    ("Bước 7: Deployment & UI", "Tối ưu hóa Dashboard Web SPA: Trực quan hóa tương tác phân bổ và Radar Chart",
     "Cho phép người dùng chọn thuật toán, điều chỉnh quota, xem phân bổ tải thời gian thực", "backend/app/static/index.html", "python run_dashboard.py", "Hoàng Văn Nam", "Chưa bắt đầu", "Giao diện mượt mà, hỗ trợ tiếng Việt có dấu"),
    ("Bước 7: Publication Figures", "Xuất bản bộ 5 biểu đồ khoa học chất lượng cao IEEE/ACM 300 DPI",
     "Learning curves, Constraint violations, Multi-algorithm comparison, System architecture, MDP flow", "outputs/figures/*.png", "python scripts/generate_figures.py", "Hoàng Văn Nam", "Chưa bắt đầu", "Hình ảnh sắc nét, chuẩn bị chèn vào luận văn"),
    ("Tuần 6: Review & Tổng kết", "Đóng gói toàn bộ mã nguồn, Dockerfile và tài liệu hướng dẫn vận hành",
     "Hệ thống có thể khởi chạy chỉ với 1 lệnh docker-compose up hoặc python run_dashboard.py", "docker-compose.yml", "docker-compose build", "Hoàng Văn Nam", "Chưa bắt đầu", "Sẵn sàng 100% phần kỹ thuật để tập trung viết báo cáo"),
]

TASKS_W7_W8 = [
    # TUẦN 7: THESIS DRAFTING & COMPILATION (02/11 - 08/11)
    ("Báo cáo Khóa luận", "Viết Chương 1 (Mở đầu, Bối cảnh, Lý do chọn đề tài, Đóng góp) & Chương 2 (Cơ sở lý thuyết Matching & RL)",
     "Làm rõ tính cấp thiết của đề tài và tổng quan các nghiên cứu liên quan", "baocao/Chuong1_Chuong2.docx", "git commit -m \"Write Chapter 1 and 2\"", "Hoàng Văn Nam", "Chưa bắt đầu", "Trích dẫn đầy đủ 25+ bài báo khoa học quốc tế"),
    ("Báo cáo Khóa luận", "Viết Chương 3 (Phân tích Yêu cầu & Dữ liệu) & Chương 4 (Biểu diễn Đặc trưng NLP & Temporal Split)",
     "Mô tả chi tiết pipeline crawl, làm sạch, audit và biểu diễn vector đề tài / giảng viên", "baocao/Chuong3_Chuong4.docx", "git commit -m \"Write Chapter 3 and 4\"", "Hoàng Văn Nam", "Chưa bắt đầu", "Bao gồm schema dữ liệu và bảng audit quality report"),
    ("Báo cáo Khóa luận", "Viết Chương 5 (Thiết kế Matching Environment & Mô hình hóa MDP Đa bước)",
     "Trình bày chi tiết toán học: State, Action, Transition, Reward, Action Masking", "baocao/Chuong5_MDP_Design.docx", "git commit -m \"Write Chapter 5 MDP Design\"", "Hoàng Văn Nam", "Chưa bắt đầu", "Chèn sơ đồ MDP Flow và công thức hàm thưởng"),
    ("Báo cáo Khóa luận", "Viết Chương 6 (Huấn luyện Thuật toán RL) & Chương 7 (Thiết kế Thực nghiệm & Baselines)",
     "Trình bày kiến trúc PPO, DQN, A2C, QR-DQN và quy trình đánh giá công bằng đa seed", "baocao/Chuong6_Chuong7.docx", "git commit -m \"Write Chapter 6 and 7\"", "Hoàng Văn Nam", "Chưa bắt đầu", "Bảng tham số siêu tham số chi tiết của từng thuật toán"),
    ("Báo cáo Khóa luận", "Viết Chương 8 (Kết quả Thực nghiệm & Phân tích Động học RL) & Chương 9 (Ablation & Stress Test)",
     "Phân tích chuyên sâu bảng số liệu, đường cong học tập, vai trò của Action Masking", "baocao/Chuong8_Chuong9.docx", "git commit -m \"Write Chapter 8 and 9\"", "Hoàng Văn Nam", "Chưa bắt đầu", "Chèn Figure 1, 2, 3 và bảng so sánh 8 thuật toán"),
    ("Báo cáo Khóa luận", "Viết Chương 10 (Thiết kế Phần mềm & Dashboard Hỗ trợ Quyết định) & Chương 11 (Vòng lặp Feedback)",
     "Trình bày kiến trúc phần mềm FastAPI + SPA và quy trình Human-in-the-loop", "baocao/Chuong10_Chuong11.docx", "git commit -m \"Write Chapter 10 and 11\"", "Hoàng Văn Nam", "Chưa bắt đầu", "Chụp ảnh giao diện Dashboard và các ca sử dụng"),
    ("Tuần 7: Review & Tổng kết", "Viết Chương 12 (Kết luận & Hướng phát triển) và tổng hợp toàn bộ Khóa luận hoàn chỉnh",
     "Hoàn thành bản thảo toàn diện Khóa luận tốt nghiệp (100-120 trang)", "baocao/KLTN_HoangVanNam_Full_Draft.docx", "git commit -m \"Complete Full Thesis Draft\"", "Hoàng Văn Nam", "Chưa bắt đầu", "Gửi bản thảo đầy đủ cho GVHD xin ý kiến nhận xét"),

    # TUẦN 8: DEFENSE PREPARATION & FINAL SUBMISSION (09/11 - 15/11)
    ("Chuẩn bị Bảo vệ", "Tiếp thu phản hồi của GVHD, chỉnh sửa hoàn thiện bản thảo luận văn theo chuẩn format NEU",
     "Rà soát lỗi chính tả, căn lề, mục lục tự động, danh mục bảng biểu, tài liệu tham khảo", "baocao/KLTN_HoangVanNam_Final.docx", "git commit -m \"Apply GVHD feedback\"", "Hoàng Văn Nam", "Chưa bắt đầu", "In thử 1 bản kiểm tra định dạng trang bìa và trang phụ"),
    ("Chuẩn bị Bảo vệ", "Thiết kế Slide thuyết trình bảo vệ Khóa luận tốt nghiệp (PowerPoint 25-30 slides)",
     "Slide súc tích, trực quan, làm nổi bật tính mới của MDP, Action Masking và kết quả thực nghiệm", "presentation/KLTN_Presentation_HoangVanNam.pptx", "PowerPoint review", "Hoàng Văn Nam", "Chưa bắt đầu", "Tuân thủ tông màu chuẩn viện CNTT&KTS NEU"),
    ("Chuẩn bị Bảo vệ", "Chuẩn bị kịch bản thuyết trình chi tiết (Script 15 phút) và bộ câu hỏi phản biện dự kiến",
     "Phân bổ thời gian: 3p Mở đầu, 4p Phương pháp RL/MDP, 5p Thực nghiệm & Đóng góp, 3p Demo", "baocao/script_thuyet_trinh_gvhd.md", "Luyện tập bấm giờ", "Hoàng Văn Nam", "Chưa bắt đầu", "Chuẩn bị sẵn câu trả lời cho các băn khoăn của hội đồng"),
    ("Chuẩn bị Bảo vệ", "Kiểm thử live demo Dashboard phân bổ sinh viên trên máy chiếu / laptop",
     "Đảm bảo ứng dụng chạy offline mượt mà không phụ thuộc vào internet của phòng hội đồng", "run_dashboard.py", "python run_dashboard.py", "Hoàng Văn Nam", "Chưa bắt đầu", "Chuẩn bị sẵn video demo dự phòng (backup video)"),
    ("Chuẩn bị Bảo vệ", "Diễn tập thuyết trình thử nghiệm lần 1 và lần 2, căn chỉnh thời lượng chính xác 15 phút",
     "Thuyết trình trôi chảy, tự tin, trả lời nhuần nhuyễn các câu hỏi phản biện", "baocao/mock_defense_notes.md", "Ghi âm / quay video thử", "Hoàng Văn Nam", "Chưa bắt đầu", "Nhờ bạn bè hoặc lab mate đóng vai hội đồng đặt câu hỏi"),
    ("Nghiệm thu & Đóng gói", "Đóng gói toàn bộ mã nguồn, checkpoints, kết quả thực nghiệm và tài liệu hướng dẫn",
     "Tạo bản sao lưu lưu trữ (Archive package) và tạo GitHub Release v1.0.0", "outputs/release/kltn_rl_matching_v1.0.0.zip", "python scripts/release_model.py", "Hoàng Văn Nam", "Chưa bắt đầu", "Bảo đảm mọi người đều có thể reproduce kết quả"),
    ("DEADLINE: 15/11/2026", "IN ĐÓNG QUYỂN KHÓA LUẬN, XIN CHỮ KÝ GVHD VÀ NỘP CHÍNH THỨC CHO KHOA/VIỆN",
     "Nộp đúng hạn 100% hồ sơ khóa luận tốt nghiệp theo đúng quy định của Trường ĐH Kinh tế Quốc dân", "Bản in bìa cứng + Đĩa CD/USB dữ liệu + Phiếu nộp", "Biên nhận nộp KLTN từ văn phòng Viện", "Hoàng Văn Nam", "Chưa bắt đầu", "DEADLINE CHÍNH THỨC 15/11/2026! Sẵn sàng bảo vệ đạt xuất sắc!"),
]

TASKS_56 = TASKS_W1_W2 + TASKS_W3_W4 + TASKS_W5_W6 + TASKS_W7_W8
