"""Pydantic schemas for Agent requests, responses, and state components."""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class StudentProfileInput(BaseModel):
    """Student academic background and preference profile."""
    student_id: Optional[str] = Field(default=None, description="Mã số sinh viên (nếu có)")
    student_name: Optional[str] = Field(default="Sinh viên", description="Họ tên sinh viên")
    gpa: Optional[float] = Field(default=3.0, ge=0.0, le=4.0, description="Điểm trung bình tích lũy thang 4")
    major: Optional[str] = Field(default="Khoa học Máy tính", description="Chuyên ngành theo học")
    skills: List[str] = Field(default_factory=list, description="Kỹ năng lập trình & công nghệ (Python, PyTorch, React,...)")
    interests: List[str] = Field(default_factory=list, description="Lĩnh vực nghiên cứu mong muốn (AI, Vision, NLP, IoT,...)")
    preliminary_topic: Optional[str] = Field(default=None, description="Ý tưởng sơ bộ về đề tài khóa luận")


class AdvisorRecommendation(BaseModel):
    """Ranked faculty advisor proposal generated by Agent."""
    advisor_id: str
    name: str
    title: Optional[str] = "ThS."
    department: str
    primary_field: str
    compatibility_score: float = Field(ge=0.0, le=1.0)
    quota_available: int = Field(default=3, description="Số lượng sinh viên có thể nhận thêm")
    justification: str = Field(description="Lý do đề xuất và đối sánh thế mạnh nghiên cứu")


class ThesisRecommendation(BaseModel):
    """Reference past thesis recommendation."""
    record_id: str
    title: str
    field_category: str
    completion_year: Optional[int] = None
    similarity_score: float = Field(ge=0.0, le=1.0)
    tech_stack: List[str] = Field(default_factory=list)


class AgentToolCallLog(BaseModel):
    """Audit log of individual tool executed by the Agent."""
    tool_name: str
    input_args: Dict[str, Any] = Field(default_factory=dict)
    output_summary: str
    duration_ms: float = 0.0


class AgentChatRequest(BaseModel):
    """Chat endpoint request body."""
    message: str = Field(..., min_length=2, description="Câu hỏi hoặc nguyện vọng làm khóa luận của sinh viên")
    student_profile: Optional[StudentProfileInput] = Field(default=None, description="Hồ sơ năng lực học tập")
    session_id: Optional[str] = Field(default=None, description="Định danh phiên hội thoại")
    stream: bool = Field(default=False, description="Bật chế độ Server-Sent Events streaming")


class AgentChatResponse(BaseModel):
    """Full structured response from LangGraph Agent."""
    answer: str = Field(..., description="Phản hồi tư vấn chi tiết từ AI Agent")
    session_id: str
    intent_detected: str
    reasoning_steps: List[str] = Field(default_factory=list, description="Các bước suy luận Chain-of-Thought")
    recommended_advisors: List[AdvisorRecommendation] = Field(default_factory=list)
    similar_theses: List[ThesisRecommendation] = Field(default_factory=list)
    tool_calls: List[AgentToolCallLog] = Field(default_factory=list)
    execution_time_ms: float = 0.0
    status: str = "success"


class MatchEvaluationRequest(BaseModel):
    """Request payload for direct student-advisor match validation."""
    student_skills: List[str]
    proposal_text: str
    advisor_id: str


class MatchEvaluationResponse(BaseModel):
    """Result of algorithmic compatibility and constraint evaluation."""
    advisor_id: str
    advisor_name: str
    compatibility_score: float
    is_quota_available: bool
    strengths: List[str]
    potential_risks: List[str]
    summary_verdict: str


class AgentHealthResponse(BaseModel):
    """Health check response schema for agent services."""
    status: str
    app_name: str
    version: str
    llm_provider: str
    active_tools_count: int
    database_connected: bool
